name: First Workflow
on: workflow_dispatch   #manually trigger this workflow
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done - bye"
